const identityIcons = {
    facebook: '/image/identities/facebook.png',
    instagram: '/image/identities/instagram.png',
    clubhouse: '/image/identities/clubhouse.png',
    venmo: '/image/identities/venmo.png',
    cashapp: '/image/identities/cashapp.png',
    behance: '/image/identities/behance.png',
    yelp: '/image/identities/yelp.png',
    resume: '/image/identities/resume.png',
    github: '/image/identities/github.png',
    reddit: '/image/identities/reddit.png',
    fbmessenger: '/image/identities/fbmessenger.png',
    slack: '/image/identities/slack.png',
    etsy: '/image/identities/Etsy.png',
    zelle: '/image/identities/zelle.png',
    opensea: '/image/identities/opensea.png',
    linktree: '/image/identities/linktree.png',
    twitter: '/image/identities/twitter.png',
    telegram: '/image/identities/telegram.png',
    appleMusic: '/image/identities/apple_music.png',
    linkedin: '/image/identities/linkedin.png',
    paypal: '/image/identities/paypal.png',
    pinterest: '/image/identities/pinterest.png',
    snapchat: '/image/identities/snapchat.png',
    spotify: '/image/identities/spotify.png',
    tiktok: '/image/identities/tiktok.png',
    twitch: '/image/identities/twitch.png',
    whatsapp: '/image/identities/whatsapp.png',
    youtube: '/image/identities/youtube.png',
    googlepay: '/image/identities/googlepay.png',
    paytm: '/image/identities/paytm.png',
    phonepe: '/image/identities/phonepe.png',
    freelancer: '/image/identities/freelancer.png',
    calendly: '/image/identities/calendlerly.png',
    youtubePlaylist: '/image/identities/youtubePlayList.png',
    linkedinCompany: '/image/identities/linkedinCompany.png'
}
export default identityIcons
