const socialLink = {
    telegram: 'https://t.me',
    twitter: 'https://twitter.com',
    facebook: 'https://facebook.com',
    // facebook: 'fb://page/',
    clubhouse: 'https://www.clubhouse.com',
    venmo: 'https://venmo.com',
    cashapp: 'https://cash.app/',
    behance: 'https://www.behance.net/',
    yelp: 'https://www.yelp.com/',
    resume: 'https://www.resume.com/',
    github: 'https://github.com/',
    reddit: 'https://www.reddit.com/',
    fbmessenger: 'https://www.messenger.com',
    slack: 'https://slack.com/intl/en-in/',
    etsy: 'https://www.etsy.com/in-en/',
    zelle: 'https://www.zellepay.com/',
    opensea: 'https://opensea.io/',
    linktree: 'https://linktr.com',
    instagram: 'https://instagram.com',
    linkedin: 'https://linkedin.com/in',
    pinterest: 'https://pinterest.com',
    twitch: 'https://twitch.tv',
    youtube: 'https://youtube.com/c',
    spotify: 'https://open.spotify.com/user',
    snapchat: 'https://snapchat.com/add',
    tiktok: 'https://vm.tiktok.com/',
    paypal: 'https://paypal.me',
    whatsapp: 'https://wa.me',
    appleMusic: 'https://music.apple.com',
    googlepay: 'https://pay.google.com?phone=',
    phonepe: 'upi://pay?pa=',
    paytm: 'paytmmp://',
    freelancer: 'https://www.freelancer.in/u/',
    calendly: 'https://calendly.com/'
}
export default socialLink
